name: deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: âœ… Checkout code
        uses: actions/checkout@v2
      
      - name: ğŸš§ Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14.x'

      - name: ğŸ› Get Packages
        run: yarn install --frozen-lockfile
      - name: ğŸ›  Build Site
        run: yarn build
      - name: ğŸ›  Export Site
        run: yarn export
      - name: ğŸŒ Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages
          folder: out
